Release/v1.1
Unity-Technologies/tk-unity pull request #116
Opened 2021-06-03 20:18 UTC by jibola1997

2021-06-04 13:31 UTC, BadSingleton approved these changes

2021-06-09 16:10 UTC, BadSingleton approved these changes

2021-06-10 13:18 UTC, BadSingleton approved these changes

2021-06-10 15:38 UTC, lassond commented on plugins/basic/bootstrap.py
> +        # Only log in bootstrap incase of an exception
"Only log" does not apply here. This was a workaround for connection issues with rpyc.
Please remove this comment as it is confusing

2021-06-10 15:38 UTC, lassond commented on plugins/basic/sg_bootstrap.py
> +The Unity bootstrap module for Shotgun. Responsible of customizing the bootstrap
Please remove the second sentence. It does not make sense now that we moved out of rpyc

2021-06-10 15:39 UTC, lassond commented on plugins/basic/sg_bootstrap.py
> +# We only initialize Shotgun once in the bootstrap process
There is no such thing as a bootstrap process. Just keep `We only initialize Shotgun once`

2021-06-10 15:39 UTC, lassond commented on plugins/basic/sg_bootstrap.py
> +        log('Shotgun is already initialized in the bootstrap process')
Change to `Shotgun is already initialized`

2021-06-10 15:40 UTC, lassond commented on plugins/basic/sg_bootstrap.py
> +        log('Shotgun has been initialized in the bootstrap process')
Change to `Shotgun has been initialized`

2021-06-10 15:40 UTC, lassond commented on plugins/basic/sg_bootstrap.py
> +        log('Shotgun has not been initialized in the bootstrap process')
Change to `Shotgun has not been initialized`

2021-06-10 15:41 UTC, lassond requested changes
Left change requests in comments

2021-06-10 18:04 UTC, BadSingleton approved these changes
LGTM

2021-06-10 18:56 UTC, lassond commented on plugins/basic/tk_create_menus/generateMenuItems.py
> +                sg_bootstrap.test_execute_menu_item(menuItem);
here is another "test_" method name.. Could you rename it? No need for me to review again if you change it

2021-06-10 18:57 UTC, lassond commented on plugins/basic/tk_create_menus/generateMenuItems.py
> +                sg_bootstrap.test_execute_menu_item(menuItem);
I love that you refactored that part by the way :-)

2021-06-10 20:03 UTC, merged